### PR TITLE
Delete src/server/EXECPP/x64 directory

### PR DESCRIPTION
**Pull request by karkub**
stare exe pracujuce s dolarom $

### CODE REVIEW

**Review by MarekDinka — APPROVED** [review]
Yay 3

**Comment by karkub** [comment]
> Yay 3

milujem xD

**Comment by pavelpetrovic** [comment]
> > Yay 3
> 
> milujem xD

milovane

6radicov

kto spravi XML pre 6 zariadeni? :)

**Comment by karkub** [comment]
Pokial sa nemylim (@IvanBohman ked tak ma oprav), ked vyberiete nejake xml (napr. [Program1.zip](https://github.com/TIS2022-FMFI/hot-air/files/12226619/Program1.zip) ) a pred stlacenim upload buttona image zaskrtnete vsetky checkboxy pri duchadlach, nove xml uz bude upravene pre 6 duchadiel.

**Comment by karkub** [comment]
XML pre 6 duchadiel [Program1_temp_control_6duchadiel.zip](https://github.com/TIS2022-FMFI/hot-air/files/12269910/Program1_temp_control_6duchadiel.zip)

**Pull request merged**
